### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by elland**
Too passive aggressive?

### CODE REVIEW

**Comment by 3lvis** [comment]
We should use a dependency manager but since right now this project is not using it, this sounds like a good idea. I would just keep it as. "Open the xcodeproj and run. The dependencies are bundled to ease our development workflow".

**Comment by elland** [comment]
> We should use a dependency manager

Why, though?

**Comment by 3lvis** [comment]
You can find more information online about why than what I can tell you here.

**Comment by elland** [comment]
@3lvis give me your most convincing link. 👍

**Comment by 3lvis** [comment]
Hahaha. Eventually I'll make some time for it.

**Comment by 3lvis** [comment]
Since the discussion is not really related to the content of the changes, could you consider them or not so we could move on with this?

**Comment by elland** [comment]
Updated.

**Comment by 3lvis** [comment]
Sounds good!

**Comment by 3lvis** [comment]
🚢

**Pull request merged**
