### PR TITLE
Tweaked the highlight script for warnings, fixmes and todos

### PR DESCRIPTION
**Pull request by elland**
What do you think?

### CODE REVIEW

**Comment by elland** [comment]
Probably not the best idea, just wondering if we should enforce that it's a `//WARNING:` so we can have `WARNING:` inside regular text, like a label, alert view etc.

**Comment by 3lvis** [comment]
Makes sense! Send it to the app-template as well, please.

**Comment by elland** [comment]
Ship it?

**Comment by 3lvis** [comment]
YES!!! :tada:

**Pull request merged**
